import os
import platform

from setuptools import find_packages, setup

def parse_requirements(filename):
    """Lee el archivo requirements.txt y devuelve una lista de dependencias."""
    with open(os.path.join(os.path.dirname(__file__), filename)) as f:
        return [line.strip() for line in f if line.strip() and not line.startswith('#')]

setup(
    name="whisperx",
    py_modules=["whisperx"],
    version="3.7.6",
    description="Time-Accurate Automatic Speech Recognition using Whisper.",
    readme="README.md",
    python_requires=">=3.10, <3.14",
    author="Max Bain",
    url="https://github.com/m-bain/whisperx",
    license="BSD-2-Clause",
    packages=find_packages(exclude=["tests*"]),
    install_requires=parse_requirements("requirements.txt") + [
        "pyannote-audio>=3.3.2,<4.0.0",
    ],
    entry_points={
        "console_scripts": ["whisperx=whisperx.__main__:cli"],
    },
    include_package_data=True,
    extras_require={"dev": ["pytest"]},
)